// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Protocol_Type int32

const (
	Protocol_CONTROL_REQ Protocol_Type = 0
	Protocol_CONTROL_RES Protocol_Type = 1
	Protocol_DATA_PACKET Protocol_Type = 2
)

var Protocol_Type_name = map[int32]string{
	0: "CONTROL_REQ",
	1: "CONTROL_RES",
	2: "DATA_PACKET",
}

var Protocol_Type_value = map[string]int32{
	"CONTROL_REQ": 0,
	"CONTROL_RES": 1,
	"DATA_PACKET": 2,
}

func (x Protocol_Type) String() string {
	return proto.EnumName(Protocol_Type_name, int32(x))
}

func (Protocol_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 0}
}

type Protocol_ControlReq_Type int32

const (
	Protocol_ControlReq_GET_NEIGHBOURS Protocol_ControlReq_Type = 0
)

var Protocol_ControlReq_Type_name = map[int32]string{
	0: "GET_NEIGHBOURS",
}

var Protocol_ControlReq_Type_value = map[string]int32{
	"GET_NEIGHBOURS": 0,
}

func (x Protocol_ControlReq_Type) String() string {
	return proto.EnumName(Protocol_ControlReq_Type_name, int32(x))
}

func (Protocol_ControlReq_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 0, 0}
}

type Protocol_DataPacket_Type int32

const (
	Protocol_DataPacket_BROADCAST Protocol_DataPacket_Type = 0
)

var Protocol_DataPacket_Type_name = map[int32]string{
	0: "BROADCAST",
}

var Protocol_DataPacket_Type_value = map[string]int32{
	"BROADCAST": 0,
}

func (x Protocol_DataPacket_Type) String() string {
	return proto.EnumName(Protocol_DataPacket_Type_name, int32(x))
}

func (Protocol_DataPacket_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 2, 0}
}

type Protocol struct {
	Type                 Protocol_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.Protocol_Type" json:"type,omitempty"`
	DataPacket           *Protocol_DataPacket `protobuf:"bytes,2,opt,name=dataPacket,proto3" json:"dataPacket,omitempty"`
	ControlReq           *Protocol_ControlReq `protobuf:"bytes,3,opt,name=controlReq,proto3" json:"controlReq,omitempty"`
	ControlRes           *Protocol_ControlRes `protobuf:"bytes,4,opt,name=controlRes,proto3" json:"controlRes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Protocol) Reset()         { *m = Protocol{} }
func (m *Protocol) String() string { return proto.CompactTextString(m) }
func (*Protocol) ProtoMessage()    {}
func (*Protocol) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0}
}

func (m *Protocol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Protocol.Unmarshal(m, b)
}
func (m *Protocol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Protocol.Marshal(b, m, deterministic)
}
func (m *Protocol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Protocol.Merge(m, src)
}
func (m *Protocol) XXX_Size() int {
	return xxx_messageInfo_Protocol.Size(m)
}
func (m *Protocol) XXX_DiscardUnknown() {
	xxx_messageInfo_Protocol.DiscardUnknown(m)
}

var xxx_messageInfo_Protocol proto.InternalMessageInfo

func (m *Protocol) GetType() Protocol_Type {
	if m != nil {
		return m.Type
	}
	return Protocol_CONTROL_REQ
}

func (m *Protocol) GetDataPacket() *Protocol_DataPacket {
	if m != nil {
		return m.DataPacket
	}
	return nil
}

func (m *Protocol) GetControlReq() *Protocol_ControlReq {
	if m != nil {
		return m.ControlReq
	}
	return nil
}

func (m *Protocol) GetControlRes() *Protocol_ControlRes {
	if m != nil {
		return m.ControlRes
	}
	return nil
}

type Protocol_ControlReq struct {
	Type                 Protocol_ControlReq_Type `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.Protocol_ControlReq_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Protocol_ControlReq) Reset()         { *m = Protocol_ControlReq{} }
func (m *Protocol_ControlReq) String() string { return proto.CompactTextString(m) }
func (*Protocol_ControlReq) ProtoMessage()    {}
func (*Protocol_ControlReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 0}
}

func (m *Protocol_ControlReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Protocol_ControlReq.Unmarshal(m, b)
}
func (m *Protocol_ControlReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Protocol_ControlReq.Marshal(b, m, deterministic)
}
func (m *Protocol_ControlReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Protocol_ControlReq.Merge(m, src)
}
func (m *Protocol_ControlReq) XXX_Size() int {
	return xxx_messageInfo_Protocol_ControlReq.Size(m)
}
func (m *Protocol_ControlReq) XXX_DiscardUnknown() {
	xxx_messageInfo_Protocol_ControlReq.DiscardUnknown(m)
}

var xxx_messageInfo_Protocol_ControlReq proto.InternalMessageInfo

func (m *Protocol_ControlReq) GetType() Protocol_ControlReq_Type {
	if m != nil {
		return m.Type
	}
	return Protocol_ControlReq_GET_NEIGHBOURS
}

type Protocol_ControlRes struct {
	From                 int64    `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Data                 string   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Protocol_ControlRes) Reset()         { *m = Protocol_ControlRes{} }
func (m *Protocol_ControlRes) String() string { return proto.CompactTextString(m) }
func (*Protocol_ControlRes) ProtoMessage()    {}
func (*Protocol_ControlRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 1}
}

func (m *Protocol_ControlRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Protocol_ControlRes.Unmarshal(m, b)
}
func (m *Protocol_ControlRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Protocol_ControlRes.Marshal(b, m, deterministic)
}
func (m *Protocol_ControlRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Protocol_ControlRes.Merge(m, src)
}
func (m *Protocol_ControlRes) XXX_Size() int {
	return xxx_messageInfo_Protocol_ControlRes.Size(m)
}
func (m *Protocol_ControlRes) XXX_DiscardUnknown() {
	xxx_messageInfo_Protocol_ControlRes.DiscardUnknown(m)
}

var xxx_messageInfo_Protocol_ControlRes proto.InternalMessageInfo

func (m *Protocol_ControlRes) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Protocol_ControlRes) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Protocol_DataPacket struct {
	Type                 Protocol_DataPacket_Type `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.Protocol_DataPacket_Type" json:"type,omitempty"`
	Data                 string                   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Protocol_DataPacket) Reset()         { *m = Protocol_DataPacket{} }
func (m *Protocol_DataPacket) String() string { return proto.CompactTextString(m) }
func (*Protocol_DataPacket) ProtoMessage()    {}
func (*Protocol_DataPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_2bc2336598a3f7e0, []int{0, 2}
}

func (m *Protocol_DataPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Protocol_DataPacket.Unmarshal(m, b)
}
func (m *Protocol_DataPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Protocol_DataPacket.Marshal(b, m, deterministic)
}
func (m *Protocol_DataPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Protocol_DataPacket.Merge(m, src)
}
func (m *Protocol_DataPacket) XXX_Size() int {
	return xxx_messageInfo_Protocol_DataPacket.Size(m)
}
func (m *Protocol_DataPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Protocol_DataPacket.DiscardUnknown(m)
}

var xxx_messageInfo_Protocol_DataPacket proto.InternalMessageInfo

func (m *Protocol_DataPacket) GetType() Protocol_DataPacket_Type {
	if m != nil {
		return m.Type
	}
	return Protocol_DataPacket_BROADCAST
}

func (m *Protocol_DataPacket) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.Protocol_Type", Protocol_Type_name, Protocol_Type_value)
	proto.RegisterEnum("protocol.Protocol_ControlReq_Type", Protocol_ControlReq_Type_name, Protocol_ControlReq_Type_value)
	proto.RegisterEnum("protocol.Protocol_DataPacket_Type", Protocol_DataPacket_Type_name, Protocol_DataPacket_Type_value)
	proto.RegisterType((*Protocol)(nil), "protocol.Protocol")
	proto.RegisterType((*Protocol_ControlReq)(nil), "protocol.Protocol.ControlReq")
	proto.RegisterType((*Protocol_ControlRes)(nil), "protocol.Protocol.ControlRes")
	proto.RegisterType((*Protocol_DataPacket)(nil), "protocol.Protocol.DataPacket")
}

func init() { proto.RegisterFile("protocol.proto", fileDescriptor_2bc2336598a3f7e0) }

var fileDescriptor_2bc2336598a3f7e0 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x03, 0x33, 0x84, 0x38, 0x60, 0x7c, 0xa5, 0x1d, 0x2c, 0x5c, 0x1c,
	0x01, 0x50, 0x8e, 0x90, 0x36, 0x17, 0x4b, 0x49, 0x65, 0x41, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x9f, 0x91, 0xb8, 0x1e, 0x5c, 0x17, 0x4c, 0x85, 0x5e, 0x48, 0x65, 0x41, 0x6a, 0x10, 0x58, 0x91,
	0x90, 0x2d, 0x17, 0x57, 0x4a, 0x62, 0x49, 0x62, 0x40, 0x62, 0x72, 0x76, 0x6a, 0x89, 0x04, 0x93,
	0x02, 0xa3, 0x06, 0xb7, 0x91, 0x2c, 0x16, 0x2d, 0x2e, 0x70, 0x45, 0x41, 0x48, 0x1a, 0x40, 0xda,
	0x93, 0xf3, 0xf3, 0x4a, 0x8a, 0xf2, 0x73, 0x82, 0x52, 0x0b, 0x25, 0x98, 0x71, 0x6a, 0x77, 0x86,
	0x2b, 0x0a, 0x42, 0xd2, 0x80, 0xa2, 0xbd, 0x58, 0x82, 0x85, 0xb0, 0xf6, 0x62, 0x24, 0xed, 0xc5,
	0x52, 0x09, 0x5c, 0x5c, 0x08, 0x83, 0x85, 0xcc, 0x50, 0xfc, 0xad, 0x84, 0xd7, 0x15, 0x48, 0x41,
	0xa0, 0x24, 0xc5, 0xc5, 0x02, 0xe2, 0x09, 0x09, 0x71, 0xf1, 0xb9, 0xbb, 0x86, 0xc4, 0xfb, 0xb9,
	0x7a, 0xba, 0x7b, 0x38, 0xf9, 0x87, 0x06, 0x05, 0x0b, 0x30, 0x48, 0x99, 0x20, 0xd9, 0x50, 0x2c,
	0x24, 0xc4, 0xc5, 0x92, 0x56, 0x94, 0x9f, 0x0b, 0xb6, 0x81, 0x39, 0x08, 0xcc, 0x06, 0x89, 0x81,
	0xc2, 0x03, 0x1c, 0x74, 0x9c, 0x41, 0x60, 0xb6, 0x54, 0x3e, 0x17, 0x17, 0x22, 0xbc, 0x88, 0x70,
	0x17, 0x42, 0x31, 0x72, 0xd4, 0x60, 0x31, 0x59, 0x49, 0x14, 0xea, 0x56, 0x5e, 0x2e, 0x4e, 0xa7,
	0x20, 0x7f, 0x47, 0x17, 0x67, 0xc7, 0xe0, 0x10, 0x01, 0x06, 0x25, 0x4b, 0xa8, 0x30, 0x3f, 0x17,
	0xb7, 0xb3, 0xbf, 0x5f, 0x48, 0x90, 0xbf, 0x4f, 0x7c, 0x90, 0x6b, 0xa0, 0x00, 0x03, 0xaa, 0x40,
	0xb0, 0x00, 0x23, 0x48, 0xc0, 0xc5, 0x31, 0xc4, 0x31, 0x3e, 0xc0, 0xd1, 0xd9, 0xdb, 0x35, 0x44,
	0x80, 0x29, 0x89, 0x0d, 0xec, 0x1c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x9b, 0xc1,
	0x4a, 0x5d, 0x02, 0x00, 0x00,
}
